use_frameworks!

target 'AppStack-Demo' do
  
  pod 'AppStack', :path => '../'
  
  pod 'Moya/RxSwift'
  
  pod 'SDWebImage'
  
end

target 'AppStack_Tests' do
  pod 'AppStack', :path => '../'
  
  pod 'Quick'
  pod 'Nimble'
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
end
