use_frameworks!
target 'AppStack_Tests' do
  pod 'AppStack', :path => '../'
  
  pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
end
